[package]
name = "guessing_game_4"
version = "0.1.0"
authors = ["Shuhei-YOSHIDA <s-yoshida@frontier.hokudai.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
