[package]
name = "practice5"
version = "0.1.0"
authors = ["Shuhei_YOSHIDA <s-yoshida@frontier.hokudai.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
